version: 2.1

jobs:
  deploy_prod:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - helm/install-helm-client:
          version: v3.0.0
      - gcp-cli/install
      - gcp-cli/initialize:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-compute-zone: GCP_COMPUTE_ZONE
          google-project-id: GCP_PROJECT_ID
      - run: gcloud --quiet container clusters get-credentials ${GCP_CLUSTER_NAME}
      - run:
          name: Deploy helm chart
          command: |
            helm upgrade --install recommender \
              --set image="dronehandelen/recommender:${CIRCLE_SHA1}" \
              --namespace production \
              ./chart

orbs:
  helm: circleci/helm@0.2.3
  gcp-cli: circleci/gcp-cli@2.1.0
  docker: circleci/docker@1.5.0

workflows:
  build_deploy:
    jobs:
      - docker/publish:
          attach-at: ./
          cache_from: dronehandelen/recommender:latest
          image: dronehandelen/recommender
          tag: ${CIRCLE_SHA1},latest
          docker-username: DOCKER_HUB_USERNAME
          docker-password: DOCKER_HUB_TOKEN
          context:
            - hub
          filters:
            branches:
              only: master
      - deploy_prod:
          context:
            - GCP
          requires:
            - docker/publish
          filters:
            branches:
              only: master
